### PR TITLE
Fixed broken patent_url links

### PR DESCRIPTION
**Pull request by ahans30**
Hi @peichman-umd and @umd-lib team,

I have fixed the broken links for the `patent_url` column in `data.csv` file. 

Previous links were expired and I have replaced them with `https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/{PATENT_NUMBER}` for given PATENT_NUMBER. 

Please note, this PR is by [GIS Data Labs at UMD Library](https://github.com/UMD-GIS-Data-Lab/) where I am Data Services GA.

Thanks,
Abhi
ahans1@umd.edu

### CODE REVIEW

**Comment by dsteelma-umd** [comment]
@AHans30,

Thank you for providing this pull request and alerting us to this issue.

There are two problems with the pull request that prevent us from using it as-is:

1) The dates in the "date" column should have the form "YYYY-MM-DD",  not "MM/DD/YYYY" . For example, for the first patent, PP00001, the "date" field should be `1931-08-18`, not `8/18/1931`.

2) The timestamps in the "scan_date" column should have the form "YYYY-MM-DD hh:mm:ss", not  "MM/DD/YYYY hh:mm". For example, for the first patent, PP00001, the "scan_date" field should be `2017-03-06 10:40:16` not `3/6/2017 10:40`.

If you could fix these issues in your submission, we would appreciate it. If not, or if you have questions about any of this, please let us know.

Thanks again.

David

**Comment by ahans30** [comment]
Hi @dsteelma-umd ,

Thanks for your note. I have fixed the `date` and `scan_date` columns such that they are in the expected format as shared by you.

I suspect this issue arose because of opening and saving files using MS Excel. In any way, they should be fixed now. If all good, please request you to go ahead and merge the PR.

Thanks,
Abhimanyu Hans
Data Services GA,
GIS and Data Lab,
UMD Libraries

**Comment by dsteelma-umd** [comment]
@AHans30,

Thanks for this correction. Unfortunately the latest submission has the following issues (which were not in the original correction):

1) The "pages" column is being formatted as a decimal value instead of an integer (i.e, as "1.0" instead of "1").

2) In the original data file, some patents have been withdrawn, and have fields contain the string "NULL", which in the corrected file have been changed to empty entries. For example:

```
PP04608,PP04608,1980-11-04,1980,NULL,PP04608 -- NULL (Withdrawn),Withdrawn,NULL,NULL,NULL,NULL,PLT/WD,,http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=PP4608,,,NULL
```

was changed to

```
PP04608,PP04608,1980-11-04,1980,,PP04608 -- NULL (Withdrawn),Withdrawn,,,,,PLT/WD,,https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/PP04608,,,
```

If you could fix these issues in your submission, we would appreciate it. If not, or if you have questions about any of this, please let us know.

Thanks again.

David

**Comment by dsteelma-umd** [comment]
@AHans30,

Thanks for your efforts on this. In the interest of getting the URLs fixed as quickly as possible, I was directed by the STEM Agriculture librarian, Isabella Baxter, to make the necessary corrections, which I have done in Pull Request #7, so I am closing this pull request without merging.

I can provide you with information on how I corrected the URLs, if you are interested.

Thanks again,

David

**Pull request closed without merging**
